[versions]
agp = "7.4.2"
kotlin = "1.8.20"
compose = "1.4.0"
dokka = "1.8.20"

ksoup = "0.1.4"
jetbrainsMarkdown = "0.3.1"

# For sample
compose-compiler = "1.4.6"
activity-compose = "1.7.0"
voyager = "1.0.0-rc05"
richeditor = "1.0.0-beta01"
android-minSdk = "21"
android-compileSdk = "33"

[libraries]
ksoup = { module = "com.mohamedrejeb.ksoup:ksoup-html", version.ref = "ksoup" }
jetbrains-markdown = { module = "org.jetbrains:markdown", version.ref = "jetbrainsMarkdown" }

# For sample
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
richeditor-compose = { module = "com.mohamedrejeb.richeditor:richeditor-compose", version.ref = "richeditor" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }